import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
